### ISSUE TITLE
Text Dropdown Node is blank with no functionality shown in the node

### ISSUE THREAD

**Issue by TheAnonymousLlama** [DadoIrie/ComfyUI_Dados_Nodes#4]
When trying to use the Text Dropdown node, all I get is a blank node with a text output.  There are no inputs and no functionality shown within the node itself.  See the screenshot below.

<img width="396" height="314" alt="Image" src="https://github.com/user-attachments/assets/19845b03-2315-4f46-826d-4ec53ddf8d0f" />

I do have dynamicprompts installed in the embedded python environment for ComfyUI.

What am I missing in order to get this to work?

Using:
ComfyUI Windows Portable: 3.50
Python: 3.12.10
pytorch: 2.7.1+cu128

**Comment by DadoIrie** [comment]
fixed
was an oversight on my end when I renamed the nodes

[effa6b0](https://github.com/DadoIrie/ComfyUI_Dados_Nodes/commit/effa6b0)

**Comment by DadoIrie** [comment]
btw this node does not need dynamicprompts and is just a simple dropdown creator - with random as option too

if playing around and testing dynamic prompts with dynamicprompts I suggest you take a look into the Wildcard Prompt Editor

**Comment by TheAnonymousLlama** [comment]
I've uninstalled and re-installed from ComfyUI Manager and it's still not showing anything in the node.  
After that didn't work, I also downloaded the file you edited specifically, DN_TextDropDownNode.js, restarted ComfyUI and same issue.

I only mentioned dyanmicprompts because it was listed as a requirement for the nodes.

**Comment by DadoIrie** [comment]
also reload browser tab since that node is mainly frontend logic
