### ISSUE TITLE
Text Dropdown is not working

### ISSUE THREAD

**Issue by cooperdk** [DadoIrie/ComfyUI_Dados_Nodes#8]
It returns a value of empty.
Also, it is badly documented (it all is). There is no way of knowing how to actually use it, including how to specify the options. I tried with a comma which seemed to work, but, it results in a text of "empty".

**Comment by DadoIrie** [comment]
issues is fixed as it was a logic oversight on my end ... but since I'm migrating from comfyui api v1 to v3 the release will take while (including documentations for all nodes)

**Comment by michimochi15** [comment]
As of now I still get a similar issue with it returning an empty value. It specifically happens right on startup of comfy. As in, it will return an empty value after I restart the software until I manually change the selected text option (despite it showing my last selection prior to restart).

As a workaround I need to toggle all my text dropdown nodes on boot, which is not feasible when I have multiple of them running.

**Comment by DadoIrie** [comment]
what's the version of my nodes you're having installed?

**Comment by DadoIrie** [comment]
workaround: after restarting comfyui reload browser tab - this should work as it triggers node creation and updates the backend with the selection

**Comment by michimochi15** [comment]
I am using version 0.10.0.
